### PR TITLE
Better fail to complete rather than blocking the UI thread for a whol…

### PR DESCRIPTION
**Pull request by cvogt**
…e second. That's the one thing an editor is not allowed to do whatever happens.

In reality this seems to sometimes prevent completion at first, but succeed after that on a maxed out MBP

### CODE REVIEW

**Comment by cvogt** [comment]
this timeout is used here: https://github.com/ensime/ensime-sublime/blob/master/rpc.py#L427 for this call https://github.com/ensime/ensime-sublime/blob/master/rpc.py#L459

**Comment by cvogt** [comment]
related discussion https://gitter.im/ensime/ensime-sublime?at=55e60ee956211cd86f8701aa

**Comment by cvogt** [comment]
tried 0.2 as well, but that is still noticeable, so I'd personally prefer 0.1. If we can figure out a non-blocking way to do completions the timeout could be much higher.

**Comment by cvogt** [comment]
actually I want to investigate more. I'll get back to you on this one. don't merge yet

**Comment by rorygraves** [comment]
@cvogt ping - I had actually forgotten about this

**Comment by cvogt** [comment]
Yeah, so last time I wasn't if this change actually interfered with other sublime features. Doesn't seem to. Everything else work fine, but I don't think completions work for me, but at least this change doesn't block the UI, which is more important. 0.2 seconds seemed to have lead to a light but noticeable lag when typing. So 0.1 is my choice. Since it seems to basically disable the feature, I am not sure if you want to apply that to master, but at the same time 1 second delay is way worse, so better to merge this than no change.

I haven't debugged the completions in more detail. I found it non-intuitive to tell if completions come from sublime itself or ensime. I guess the log would help, but I don't have time to investigate right now.

**Comment by cvogt** [comment]
P.S. how did all the other commits end up in here? Did you rebase the public master?

**Comment by rorygraves** [comment]
@cvogt Yes, I was a bit naughty - I've basically force pushed the master branch to be the ST3 branch rather than the ST2 branch (as only ST3 is being actively fixed it seemed to make sense)

In terms of times, there are a couple of things we can do - 1 we could make it a configurable option in the plugin.  It would also be nice to understand where that time is going - hopefully I will get time to look at it soon.

**Comment by cvogt** [comment]
Not sure I understand. It is a configurable option in the plugin. My commit changes it's default config value, because the default value gives a bad UX. I am afraid this instantly drives away people who quickly try ensime, before they even give it a chance and look for a config option.

**Comment by dickwall** [comment]
I still have yet to see this happen with the larger timeout, and am hesitant to merge until I do. We need to make sure this is not just a feature of @cvogt's machine :-). Can you supply a project and completion point where this can be reliably reproduced for a second or more? I will up my timeout to several seconds and see if I can get it to block. I can also look at why it takes so darn long in that situation as there might be another fix.

Thanks

**Comment by cvogt** [comment]
I think there can be a theoretical point made that blocking for 1 second can't be a good idea, even if it just happens on some people's machines. It's just not a good default.

But theory aside, I can replicate the problem in all 3 projects I just tried.

**Steps to reproduce:**
* add `addSbtPlugin("org.ensime" % "ensime-sbt" % "0.2.0")` to your `global.sbt`
* update sublime-ensime plugin to latest master
* `git clone git@github.com:cvogt/scala-dash.git`
* `cd scala-dash`
* `sbt gen-ensime`
* In sublime `Ensime startup
* open `scala-hash.scala`
* place the cursor right behind `object ScalaDashDocsetBuilder{`
* press enter
* Then start typing `"t`

Right there it blocks. In fact now I see it even crashes ensime-sublime - it stops. I don't think that happened in all projects, but it also happened with the 0.1.7 plugin and the older sublime-ensime plugin I was using before I just updated.

server output
```
org.parboiled.errors.ParsingException: Invalid :
Unexpected end of input, expected Comment, ' ', '\n', '\r', '\t', '\f', Whitespace, Sexp or ) (line 377, pos 20):
") 78 100 nil nil)
                   ^

	at org.ensime.sexp.util.ParboiledParser$$anonfun$parse$1.apply(ParboiledParser.scala:23) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.util.ParboiledParser$$anonfun$parse$1.apply(ParboiledParser.scala:23) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.7.jar:na]
	at org.ensime.sexp.util.ParboiledParser$class.parse(ParboiledParser.scala:22) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpParser$.parse(SexpParser.scala:11) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.PimpedString.parseSexp(package.scala:17) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.SwankProtocol.decode(SwankProtocol.scala:14) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor.repeatedDecode(TCPConnectionActor.scala:104) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor.attemptProcess(TCPConnectionActor.scala:93) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor$$anonfun$incoming$1.applyOrElse(TCPConnectionActor.scala:45) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) ~[scala-library-2.11.7.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.12.jar:na]
	at org.ensime.server.tcp.TCPConnectionActor.aroundReceive(TCPConnectionActor.scala:15) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
```

Sublime console output
```
reloading /Users/user/Library/Application Support/Sublime Text 3/Packages/Ensime/logs/client.log
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/Ensime/ensime.py", line 80, in log_on_ui_thread
    f.write(self.prepare_log_message(data))
UnicodeEncodeError: 'ascii' codec can't encode character '\xb7' in position 1568: ordinal not in range(128)

Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/Ensime/ensime.py", line 80, in log_on_ui_thread
    f.write(self.prepare_log_message(data))
UnicodeEncodeError: 'ascii' codec can't encode character '\xb7' in position 1583: ordinal not in range(128)

Controller shutdown() called
shutdown() called
reloading /Users/user/Library/Application Support/Sublime Text 3/Packages/Ensime/logs/client.log
```

client.log output
```
[2015-09-12 01:45:42.145296]: sync_req #2 has timed out (didn't get a response after 2 seconds)
[2015-09-12 01:45:42.149231]: *****    ERROR     *****
[2015-09-12 01:45:42.149392]: Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/Ensime/ensime.py", line 445, in receive_loop
    msglen = self.socket.recv(6)
ConnectionResetError: [Errno 54] Connection reset by peer
```

**Comment by rorygraves** [comment]
@cvogt This is a sign of a different bug that I have just fixed on my branch.  Completion without save on files with utf-8 chars in in was broken because it encoded the wrong message length.
Try using my branch https://github.com/rorygraves/ensime-sublime/tree/ST3  @dickwall  has been running for a bit so it seems mostly stable.

**Comment by cvogt** [comment]
with that I get a 
```
  ...
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/Ensime/paths.py", line 22, in decode_path
    if os.name == "nt":
AttributeError: 'NoneType' object has no attribute 'name'
```
some googling hints to libraries maybe not being on the path, not sure how that works with sublimes python.

**Comment by cvogt** [comment]
(ignore my previous deleted posting, I had to restart sublime)

**Comment by cvogt** [comment]
ok, with that branch, ensime doesn't crash anymore. Typing fast in the string literal shows noticeable delays every few characters around 0.3 - 0.4 seconds. So not as long as my timeout which I configured to be 2s, but very noticeable. Why is that?

The server shows
```
[Ensime] 2015-09-12 03:42:00,939 [ensime-clien] [INFO ]  request #1 took 0.1747579574584961 seconds
[Ensime] 2015-09-12 03:42:38,859 [ensime-clien] [INFO ]  request #2 took 0.7081880569458008 seconds
[Ensime] 2015-09-12 03:42:41,446 [ensime-clien] [INFO ]  request #3 took 0.5210440158843994 seconds
[Ensime] 2015-09-12 03:42:41,976 [ensime-clien] [INFO ]  request #4 took 0.44607996940612793 seconds
[Ensime] 2015-09-12 03:42:43,523 [ensime-clien] [INFO ]  request #5 took 0.41367101669311523 seconds
[Ensime] 2015-09-12 03:42:44,003 [ensime-clien] [INFO ]  request #6 took 0.405548095703125 seconds
[Ensime] 2015-09-12 03:42:44,432 [ensime-clien] [INFO ]  request #7 took 0.36978888511657715 seconds
[Ensime] 2015-09-12 03:42:45,943 [ensime-clien] [INFO ]  request #8 took 0.3672349452972412 seconds
[Ensime] 2015-09-12 03:42:46,362 [ensime-clien] [INFO ]  request #9 took 0.34909796714782715 seconds
[Ensime] 2015-09-12 03:42:46,790 [ensime-clien] [INFO ]  request #10 took 0.3670070171356201 seconds
[Ensime] 2015-09-12 03:42:47,179 [ensime-clien] [INFO ]  request #11 took 0.3272261619567871 seconds
[Ensime] 2015-09-12 03:42:47,577 [ensime-clien] [INFO ]  request #12 took 0.3278679847717285 seconds
[Ensime] 2015-09-12 03:42:48,000 [ensime-clien] [INFO ]  request #13 took 0.34868812561035156 seconds
[Ensime] 2015-09-12 03:42:48,551 [ensime-clien] [INFO ]  request #14 took 0.3616669178009033 seconds
[Ensime] 2015-09-12 03:42:49,030 [ensime-clien] [INFO ]  request #15 took 0.34959888458251953 seconds
[Ensime] 2015-09-12 03:42:49,587 [ensime-clien] [INFO ]  request #16 took 0.34948086738586426 seconds
[Ensime] 2015-09-12 03:42:50,191 [ensime-clien] [INFO ]  request #17 took 0.3695390224456787 seconds
[Ensime] 2015-09-12 03:42:50,906 [ensime-clien] [INFO ]  request #18 took 0.35790491104125977 seconds
[Ensime] 2015-09-12 03:42:51,699 [ensime-clien] [INFO ]  request #19 took 0.384005069732666 seconds
[Ensime] 2015-09-12 03:42:52,085 [ensime-clien] [INFO ]  request #20 took 0.32831788063049316 seconds
```

If I try to open the client log in your branch I get this exception in the sublime console
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 535, in run_
    return self.run()
  File "/Users/chris/Library/Application Support/Sublime Text 3/Packages/Ensime/ensime.py", line 1341, in run
    _show_log(self, "client.log")
  File "/Users/chris/Library/Application Support/Sublime Text 3/Packages/Ensime/ensime.py", line 1326, in _show_log
    log = self.env.log_root + os.sep + file_name
AttributeError: 'EnsimeEnvironment' object has no attribute 'log_root'
```

But I do see ensime related messages in the console. Did you redirect it there?

**Comment by cvogt** [comment]
In the bigger project I mentioned, completions work now and I get delays between 1 and 1.5 seconds when I first start typing in a line. Method completions seem more on the level of 1 second. (You are probably aware of that, but if they time out, it seems the plugins disables completions temporarily, not sure what causes them to work again, Ensime restart for sure.)

Completions log.
```
[Ensime] 2015-09-12 03:55:11,366 [ensime-clien] [INFO ]  request #48 took 0.9976270198822021 seconds
[Ensime] 2015-09-12 03:55:14,579 [ensime-clien] [INFO ]  request #49 took 1.0692260265350342 seconds
[Ensime] 2015-09-12 03:55:17,225 [ensime-clien] [INFO ]  request #50 took 1.3344740867614746 seconds
[Ensime] 2015-09-12 03:55:20,438 [ensime-clien] [INFO ]  request #51 took 1.3171210289001465 seconds
[Ensime] 2015-09-12 03:55:36,037 [ensime-clien] [INFO ]  request #52 took 0.004634857177734375 seconds
[Ensime] 2015-09-12 03:55:44,172 [ensime-clien] [INFO ]  request #53 took 0.0038690567016601562 seconds
[Ensime] 2015-09-12 03:55:46,875 [ensime-clien] [INFO ]  request #54 took 0.003304004669189453 seconds
[Ensime] 2015-09-12 03:55:49,206 [ensime-clien] [INFO ]  request #55 took 0.0032989978790283203 seconds
[Ensime] 2015-09-12 03:55:52,193 [ensime-clien] [INFO ]  request #56 took 1.5731821060180664 seconds
[Ensime] 2015-09-12 03:55:55,073 [ensime-clien] [INFO ]  request #57 took 1.3625550270080566 seconds
[Ensime] 2015-09-12 03:56:05,682 [ensime-clien] [INFO ]  request #58 took 0.0033071041107177734 seconds
[Ensime] 2015-09-12 03:56:06,880 [ensime-clien] [INFO ]  request #59 took 0.003268003463745117 seconds
[Ensime] 2015-09-12 03:56:14,961 [ensime-clien] [INFO ]  request #60 took 1.250791072845459 seconds
[Ensime] 2015-09-12 03:56:26,664 [ensime-clien] [INFO ]  request #61 took 1.4497120380401611 seconds
```

Server says 
```
03:56:14.721 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con2/60 o.e.s.RequestHandler - CompletionsReq(SourceFileInfo(/Users/user/Foo.scala,Some(...),None),4577,100,false,false)
03:56:14.721 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message CompletionsReq(SourceFileInfo(/Users/user/Foo.scala,Some(...),None),4577,100,false,false)
03:56:14.721 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message CompletionsReq(SourceFileInfo(/Users/user/Foo.scala,Some(...),None),4577,100,false,false) in state ready
03:56:14.741 DEBUG None o.e.c.RichPresentationCompiler - Completing at tree:Ident(a)
03:56:14.814 INFO  None o.e.c.RichPresentationCompiler - Found 3482 members.
03:56:14.821 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.c.RichPresentationCompiler - Filtered down to 3482.
03:56:14.931 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con2/60 o.e.s.RequestHandler - received handled message CompletionInfoList(,List(CompletionInfo(^,CompletionSignature(List(List((fa,<byname>[F[A]]), (fb,<byname>[F[B]])), List((f,Function2[A, B, C])), List((F,Apply[F]))),F[C]),2588,true,90,None), CompletionInfo(∅,CompletionSignatu
```

So I basically get 1-1.5 seconds delay when I start typing in a new line. I guess with the current implementation that sure means choosing between having delay or basically disabling the feature for this project. 

In the one file 3 library scala-dash project I get 0.3-0.4 seconds delays when starting to type in a line, which seems just on the border where it is annoying but not killing.

Maybe it can be implemented in an async way as @dickwall indicated he may want to investigate.

Thx guys, this all brings more clarity. Not sure what to do about user experience though. Delays are bad, but not having completions skips one of ensime's core features. Maybe allow people to switch it of in the settings and include info about it in the default user settings, that people have to touch anyways?

**Comment by cvogt** [comment]
closing this for now

**Comment by rorygraves** [comment]
On 12/09/2015 09:10, Jan Christopher Vogt wrote:
> Completions log.
> |[Ensime] 2015-09-12 03:56:14,961 [ensime-clien] [INFO ]  request #60 took 1.250791072845459 seconds
> |Server says
> |03:56:14.721 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con2/60 o.e.s.RequestHandler - CompletionsReq(SourceFileInfo(/Users/user/Foo.scala,Some(...),None),4577,100,false,false)
> 03:56:14.721 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message CompletionsReq(SourceFileInfo(/Users/user/Foo.scala,Some(...),None),4577,100,false,false)
> 03:56:14.721 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message CompletionsReq(SourceFileInfo(/Users/user/Foo.scala,Some(...),None),4577,100,false,false) in state ready
> 03:56:14.741 DEBUG None o.e.c.RichPresentationCompiler - Completing at tree:Ident(a)
> 03:56:14.814 INFO  None o.e.c.RichPresentationCompiler - Found 3482 members.
> 03:56:14.821 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.c.RichPresentationCompiler - Filtered down to 3482.
> 03:56:14.931 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con2/60 o.e.s.RequestHandler - received handled message CompletionInfoList(,List(CompletionInfo(^,CompletionSignature(List(List((fa,<byname>[F[A]]), (fb,<byname>[F[B]])), List((f,Function2[A, B, C])), List((F,Apply[F]))),F[C]),2588,true,90,None), CompletionInfo(∅,CompletionSignatu|
There is something funky here - client says it took 1.25sec - total 
server mesage processing time 210ms - but (assuming the client and 
server logs tie up the timestamps make it look like it the server didn't 
see it for the first second.

I notice in the log here that the file is being sent as it has not been 
written to the disk.

If you get to it before I do (I'm not gong to get to it before at least 
tuesday - then I suggest using my branch and adding some mroe logging 
statments around _query_completions() and raising the logging in 
sync_req to be visible (i.e. above debug).

The delays are bad and appear to be much worse than I would expect (esp 
given the server log).

**Pull request closed without merging**
