### PR TITLE
Show type info as popup menu along with links to lookup symbol

### PR DESCRIPTION
**Pull request by jerchung**
Just some added some Intellij like functionality of the alt-click bringing up a tooltip (Using sublime text 3's fairly limited tooltip API).  Also each separate type in the tooltip becomes a link which can be clicked into to jump to the source.

screen shot 2015-08-04 at 10 27 42 pm

screen shot 2015-08-04 at 10 25 30 pm

First image shows what alt-click does on a method, then second picture is what happens if you click on RangePosition.  I don't know any way to style the tooltip that pops up beyond the font size / maximum size of the tooltip (again, the API is fairly limited).

### CODE REVIEW

**Comment by rorygraves** [comment]
@jerchung Very cool!
I will check this out tonight.

**Comment by dickwall** [comment]
oh hells yeah - trying it out right now.

**Comment by dickwall** [comment]
OK - two comments on this - neither of them are show-stoppers:

First, is there any chance the amount of whitespace above and below can be reduced, particularly on short types it looks a little odd.

Second, in my settings I have set inspect type on any mouse click rather than just alt-click. This means it still comes up any time I just click in the window. I could turn that off (although I like seeing the type in the status bar when I click on a type without alt-click) so I just wanted to throw that out for ideas in case there is another alternative?

Otherwise, it seems to work very nicely.

**Comment by jerchung** [comment]
@dickwall
Thanks for the feedback!  After some experimentation it seems I was doing something subtly wrong generating the tooltip and making the spacing off.  Here's what the new tooltip looks like:

screen shot 2015-08-05 at 10 44 29 pm

For your second point, one solution might be to expose 2 classes in ensime.py `EnsimeInspectTypeStatusMessage` to show a status message for the type and `EnsimeInspectTypeTooltip` to show a tooltip.  Then you can key / mousebind to either class depending on what you want.  I can add something like that in tomorrow when I have time.

**Comment by dickwall** [comment]
Jerry, great minds and all that. I had exactly the same thought - two different routines, one works like the old one, status bar based, and the new one with the popup, then, as you say, you can bind differently and accordingly. Incidentally, I have noticed a side benefit of the popup. When you get a compile error on a line, the error tends to take up the whole status bar pushing any type information off of it. With the popup, you can still see the error in the status bar AND get popup type information to help fix it, which is a real win.

Excellent work. Will wait for the updated PR.

**Comment by rorygraves** [comment]
I promised feedback and failed, but I feel that @dickwall has stepped up to the plate, so go for it gents!

**Comment by jerchung** [comment]
@dickwall would you mind posting what your user sublime-mousemap file looks like to get the type info working with just a left mouse click?

I made a separate class to get the type info to show up on the status bar, but when I added this setting to the mousemap, I could not longer left click anywhere (the cursor wouldn't appear where I clicked), and the type info didn't show up.

```
{
    "button": "button1", "count": 1,
    "press_command": "ensime_single_click",
    "press_args": {"command": "drag_select", "args": {"subtractive": true}}
}
```

The ensime_single_click is just like ensime_alt_click which calls another TypeInfo command on the active view.

**Comment by dickwall** [comment]
sure - this is on linux, so on Mac (I am guessing here) ymmv, but what I have is just:

```
[
    {
        "button": "button1", 
        "count": 1, 
        "modifiers": [],
        "press_command": "drag_select",
        "command": "ensime_inspect_type_at_point"
    }
]
```

This is with the old impl, I am about to try and adapt this to call your ensime_single_click so I'll let you know how that goes.

**Comment by dickwall** [comment]
Ok - with this latest one I am seeing the following error in the console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 148, in create_text_commands
    cmds.append(class_(view))
  File "/Users/rlwall2/Library/Application Support/Sublime Text 3/Packages/Ensime/ensime.py", line 181, in __init__
    class EnsimeTextCommand(EnsimeCommon, TextCommand):
TypeError: super(type, obj): obj must be an instance or subtype of type
```

My python is shockingly rusty. I don't see anything particularly wrong with those superclasses (they are used elsewhere without problem). Any idea what the issue is here?

**Comment by dickwall** [comment]
Please ignore the above, not sure why it happened, but restarting sublime cleaned it up - maybe a dirty cached pyc or something. Testing out the new functionality now, if it works out, Rory you OK with me merging in?

**Comment by dickwall** [comment]
Sweeeeet, these mouse bindings work beautifully:

```
[
    {
        "button": "button1", 
        "count": 1, 
        "modifiers": [],
        "press_command": "drag_select",
        "command": "ensime_inspect_type_at_point_status"
    },
    {
        "button": "button1", 
        "count": 1, 
        "modifiers": ["alt"],
        "press_command": "drag_select",
        "command": "ensime_inspect_type_at_point_tooltip"
    }
]
```

Single click brings up status typing, alt click brings up the tooltip.

Nice job Jerry. Thanks

**Comment by dickwall** [comment]
OK - the final bit of fiddling, now it's all perfect:

```
[
    {
        "button": "button1", 
        "count": 1, 
        "modifiers": [],
        "press_command": "drag_select",
        "command": "ensime_inspect_type_at_point_status"
    },
    {
        "button": "button1", 
        "count": 1, 
        "modifiers": ["alt"],
        "press_command": "drag_select",
        "press_args": {"by": "columns"},
        "command": "ensime_inspect_type_at_point_tooltip"
    }

]
```

This restores column select on the alt click as well, which I noticed was broken from my previous settings.

**Comment by rorygraves** [comment]
Yeah go for it.

**Pull request merged**
